apiVersion: v1
kind: LimitRange
metadata:
  name: ai-limits
  namespace: ai
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "2"
        memory: "8Gi"
      default:
        cpu: "4"
        memory: "16Gi"
      min:
        cpu: "1"
        memory: "4Gi"
      max:
        cpu: "16"
        memory: "96Gi"
