apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-quota
  namespace: ai
spec:
  hard:
    pods: "8"

    requests.cpu: "8"
    limits.cpu: "12"

    requests.memory: "48Gi"
    limits.memory: "112Gi"

    persistentvolumeclaims: "8"
    requests.storage: "500Gi"
