apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
