apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox-limits
  namespace: sandbox
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      default:
        cpu: "200m"
        memory: "256Mi"
      min:
        cpu: "25m"
        memory: "32Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
