apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-12-19T05:32:49Z"
  labels:
    kubernetes.io/metadata.name: infra
  name: infra
  resourceVersion: "1026"
  uid: ce02bc2c-5b73-42c3-89d6-b6ce4b835edd
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
